/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.utilis;

/**
 *
 * @author Ben Gouta Monam
 */
public class Newmailevent {

   public static String s1 = "<!DOCTYPE html\n"
            + "    PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
            + "<html xmlns='http://www.w3.org/1999/xhtml' xmlns:o='urn:schemas-microsoft-com:office:office'\n"
            + "    style='width:100%;font-family:arial, ' helvetica neue', helvetica,\n"
            + "    sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0'>\n"
            + "\n"
            + "<head>\n"
            + "    <meta charset='UTF-8'>\n"
            + "    <meta content='width=device-width, initial-scale=1' name='viewport'>\n"
            + "    <meta name='x-apple-disable-message-reformatting'>\n"
            + "    <meta http-equiv='X-UA-Compatible' content='IE=edge'>\n"
            + "    <meta content='telephone=no' name='format-detection'>\n"
            + "    <title></title>\n"
            + "    <!--[if (mso 16)]><style type='text/css'>     a {text-decoration: none;}     </style><![endif]-->\n"
            + "    <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]-->\n"
            + "    <!--[if gte mso 9]><xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml><![endif]-->\n"
            + "    <link rel='icon' href='../../Assets/favicon.ico'>\n"
            + "    <style type='text/css'>\n"
            + "        .section-title {\n"
            + "            padding: 5px 10px;\n"
            + "            background-color: #f6f6f6;\n"
            + "            border: 1px solid #dfdfdf;\n"
            + "            outline: 0;\n"
            + "        }\n"
            + "\n"
            + "        .custom_accordion.section-title {\n"
            + "            background-color: transparent;\n"
            + "            border: none;\n"
            + "        }\n"
            + "\n"
            + "        #outlook a {\n"
            + "            padding: 0;\n"
            + "        }\n"
            + "\n"
            + "        .amp-carousel-button {\n"
            + "            border-radius: 12px;\n"
            + "            border-left: 4px solid #3333ff;\n"
            + "            border-bottom: 2px solid #3333ff;\n"
            + "        }\n"
            + "\n"
            + "        .ExternalClass {\n"
            + "            width: 100%;\n"
            + "        }\n"
            + "\n"
            + "        .ExternalClass,\n"
            + "        .ExternalClass p,\n"
            + "        .ExternalClass span,\n"
            + "        .ExternalClass font,\n"
            + "        .ExternalClass td,\n"
            + "        .ExternalClass div {\n"
            + "            line-height: 100%;\n"
            + "        }\n"
            + "\n"
            + "        .es-button {\n"
            + "            mso-style-priority: 100 !important;\n"
            + "            text-decoration: none !important;\n"
            + "        }\n"
            + "\n"
            + "        a[x-apple-data-detectors] {\n"
            + "            color: inherit !important;\n"
            + "            text-decoration: none !important;\n"
            + "            font-size: inherit !important;\n"
            + "            font-family: inherit !important;\n"
            + "            font-weight: inherit !important;\n"
            + "            line-height: inherit !important;\n"
            + "        }\n"
            + "\n"
            + "        .es-desk-hidden {\n"
            + "            display: none;\n"
            + "            float: left;\n"
            + "            overflow: hidden;\n"
            + "            width: 0;\n"
            + "            max-height: 0;\n"
            + "            line-height: 0;\n"
            + "            mso-hide: all;\n"
            + "        }\n"
            + "\n"
            + "        @media only screen and (max-width:600px) {\n"
            + "\n"
            + "            p,\n"
            + "            ul li,\n"
            + "            ol li,\n"
            + "            a {\n"
            + "                line-height: 150% !important\n"
            + "            }\n"
            + "\n"
            + "            h1 {\n"
            + "                font-size: 30px !important;\n"
            + "                text-align: center;\n"
            + "                line-height: 120%\n"
            + "            }\n"
            + "\n"
            + "            h2 {\n"
            + "                font-size: 26px !important;\n"
            + "                text-align: left;\n"
            + "                line-height: 120%\n"
            + "            }\n"
            + "\n"
            + "            h3 {\n"
            + "                font-size: 20px !important;\n"
            + "                text-align: left;\n"
            + "                line-height: 120%\n"
            + "            }\n"
            + "\n"
            + "            h1 a {\n"
            + "                text-align: center\n"
            + "            }\n"
            + "\n"
            + "            .es-header-body h1 a,\n"
            + "            .es-content-body h1 a,\n"
            + "            .es-footer-body h1 a {\n"
            + "                font-size: 30px !important\n"
            + "            }\n"
            + "\n"
            + "            h2 a {\n"
            + "                text-align: left\n"
            + "            }\n"
            + "\n"
            + "            .es-header-body h2 a,\n"
            + "            .es-content-body h2 a,\n"
            + "            .es-footer-body h2 a {\n"
            + "                font-size: 26px !important\n"
            + "            }\n"
            + "\n"
            + "            h3 a {\n"
            + "                text-align: left\n"
            + "            }\n"
            + "\n"
            + "            .es-header-body h3 a,\n"
            + "            .es-content-body h3 a,\n"
            + "            .es-footer-body h3 a {\n"
            + "                font-size: 20px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-menu td a {\n"
            + "                font-size: 14px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-header-body p,\n"
            + "            .es-header-body ul li,\n"
            + "            .es-header-body ol li,\n"
            + "            .es-header-body a {\n"
            + "                font-size: 12px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-content-body p,\n"
            + "            .es-content-body ul li,\n"
            + "            .es-content-body ol li,\n"
            + "            .es-content-body a {\n"
            + "                font-size: 14px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-footer-body p,\n"
            + "            .es-footer-body ul li,\n"
            + "            .es-footer-body ol li,\n"
            + "            .es-footer-body a {\n"
            + "                font-size: 12px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-infoblock p,\n"
            + "            .es-infoblock ul li,\n"
            + "            .es-infoblock ol li,\n"
            + "            .es-infoblock a {\n"
            + "                font-size: 12px !important\n"
            + "            }\n"
            + "\n"
            + "            *[class='gmail-fix'] {\n"
            + "                display: none !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-txt-c,\n"
            + "            .es-m-txt-c h1,\n"
            + "            .es-m-txt-c h2,\n"
            + "            .es-m-txt-c h3 {\n"
            + "                text-align: center !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-txt-r,\n"
            + "            .es-m-txt-r h1,\n"
            + "            .es-m-txt-r h2,\n"
            + "            .es-m-txt-r h3 {\n"
            + "                text-align: right !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-txt-l,\n"
            + "            .es-m-txt-l h1,\n"
            + "            .es-m-txt-l h2,\n"
            + "            .es-m-txt-l h3 {\n"
            + "                text-align: left !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-txt-r img,\n"
            + "            .es-m-txt-c img,\n"
            + "            .es-m-txt-l img {\n"
            + "                display: inline !important\n"
            + "            }\n"
            + "\n"
            + "            .es-button-border {\n"
            + "                display: inline-block !important\n"
            + "            }\n"
            + "\n"
            + "            .es-btn-fw {\n"
            + "                border-width: 10px 0px !important;\n"
            + "                text-align: center !important\n"
            + "            }\n"
            + "\n"
            + "            .es-adaptive table,\n"
            + "            .es-btn-fw,\n"
            + "            .es-btn-fw-brdr,\n"
            + "            .es-left,\n"
            + "            .es-right {\n"
            + "                width: 100% !important\n"
            + "            }\n"
            + "\n"
            + "            .es-content table,\n"
            + "            .es-header table,\n"
            + "            .es-footer table,\n"
            + "            .es-content,\n"
            + "            .es-footer,\n"
            + "            .es-header {\n"
            + "                width: 100% !important;\n"
            + "                max-width: 600px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-adapt-td {\n"
            + "                display: block !important;\n"
            + "                width: 100% !important\n"
            + "            }\n"
            + "\n"
            + "            .adapt-img {\n"
            + "                width: 100% !important;\n"
            + "                height: auto !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-p0 {\n"
            + "                padding: 0px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-p0r {\n"
            + "                padding-right: 0px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-p0l {\n"
            + "                padding-left: 0px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-p0t {\n"
            + "                padding-top: 0px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-p0b {\n"
            + "                padding-bottom: 0 !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-p20b {\n"
            + "                padding-bottom: 20px !important\n"
            + "            }\n"
            + "\n"
            + "            .es-mobile-hidden,\n"
            + "            .es-hidden {\n"
            + "                display: none !important\n"
            + "            }\n"
            + "\n"
            + "            tr.es-desk-hidden,\n"
            + "            td.es-desk-hidden,\n"
            + "            table.es-desk-hidden {\n"
            + "                width: auto !important;\n"
            + "                overflow: visible !important;\n"
            + "                float: none !important;\n"
            + "                max-height: inherit !important;\n"
            + "                line-height: inherit !important\n"
            + "            }\n"
            + "\n"
            + "            tr.es-desk-hidden {\n"
            + "                display: table-row !important\n"
            + "            }\n"
            + "\n"
            + "            table.es-desk-hidden {\n"
            + "                display: table !important\n"
            + "            }\n"
            + "\n"
            + "            td.es-desk-menu-hidden {\n"
            + "                display: table-cell !important\n"
            + "            }\n"
            + "\n"
            + "            .es-menu td {\n"
            + "                width: 1% !important\n"
            + "            }\n"
            + "\n"
            + "            table.es-table-not-adapt,\n"
            + "            .esd-block-html table {\n"
            + "                width: auto !important\n"
            + "            }\n"
            + "\n"
            + "            table.es-social {\n"
            + "                display: inline-block !important\n"
            + "            }\n"
            + "\n"
            + "            table.es-social td {\n"
            + "                display: inline-block !important\n"
            + "            }\n"
            + "\n"
            + "            .es-m-margin {\n"
            + "                padding-left: 10px !important;\n"
            + "                padding-right: 10px !important;\n"
            + "                padding-top: 0px !important;\n"
            + "                padding-bottom: 0px !important\n"
            + "            }\n"
            + "\n"
            + "            a.es-button,\n"
            + "            button.es-button {\n"
            + "                font-size: 12px !important;\n"
            + "                display: inline-block !important\n"
            + "            }\n"
            + "        }\n"
            + "    </style>\n"
            + "</head>\n"
            + "\n"
            + "<body style='width:100%;font-family:arial, ' helvetica neue', helvetica,\n"
            + "    sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0'>\n"
            + "    <div class='es-wrapper-color' style='background-color:transparent'>\n"
            + "        <!--[if gte mso 9]><v:background xmlns:v='urn:schemas-microsoft-com:vml' fill='t'> <v:fill type='tile' color='transparent'></v:fill> </v:background><![endif]-->\n"
            + "        <table class='es-wrapper' width='100%' cellspacing='0' cellpadding='0'\n"
            + "            style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top'>\n"
            + "            <tr style='border-collapse:collapse'>\n"
            + "                <td class='es-m-margin' valign='top' style='padding:0;Margin:0'>\n"
            + "                    <table cellpadding='0' cellspacing='0' class='es-header' align='center'\n"
            + "                        style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top'>\n"
            + "                        <tr style='border-collapse:collapse'>\n"
            + "                            <td align='center' style='padding:0;Margin:0'>\n"
            + "                                <table bgcolor='#ffffff' class='es-header-body' align='center' cellpadding='0'\n"
            + "                                    cellspacing='0'\n"
            + "                                    style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:640px'>\n"
            + "                                    <tr style='border-collapse:collapse'>\n"
            + "                                        <td align='left'\n"
            + "                                            style='padding:0;Margin:0;padding-top:30px;padding-bottom:30px'>\n"
            + "                                            <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                <tr style='border-collapse:collapse'>\n"
            + "                                                    <td align='center' valign='top'\n"
            + "                                                        style='padding:0;Margin:0;width:640px'>\n"
            + "                                                        <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                            style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                            <tr style='border-collapse:collapse'>\n"
            + "                                                                <td align='center'\n"
            + "                                                                    style='padding:0;Margin:0;padding-top:5px;font-size:0px'>\n"
            + "                                                                    <a target='_blank' href='https://viewstripo.email'\n"
            + "                                                                        style='-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:14px'><img\n"
            + "                                                                            src='https://www.logaster.fr/blog/wp-content/uploads/sites/9/2019/03/0036_t_art-logo_12.png'\n"
            + "                                                                            alt\n"
            + "                                                                            style='display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic'\n"
            + "                                                                            width='128'></a>\n"
            + "                                                                </td>\n"
            + "                                                            </tr>\n"
            + "                                                        </table>\n"
            + "                                                    </td>\n"
            + "                                                </tr>\n"
            + "                                            </table>\n"
            + "                                        </td>\n"
            + "                                    </tr>\n"
            + "                                </table>\n"
            + "                            </td>\n"
            + "                        </tr>\n"
            + "                    </table>\n"
            + "                    <table class='es-content' cellspacing='0' cellpadding='0' align='center'\n"
            + "                        style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%'>\n"
            + "                        <tr style='border-collapse:collapse'>\n"
            + "                            <td align='center' style='padding:0;Margin:0'>\n"
            + "                                <table class='es-content-body' cellspacing='0' cellpadding='0' bgcolor='#ffffff'\n"
            + "                                    align='center'\n"
            + "                                    style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:640px'>\n"
            + "                                    <tr style='border-collapse:collapse'>\n"
            + "                                        <td align='left' style='padding:0;Margin:0'>\n"
            + "                                            <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                <tr style='border-collapse:collapse'>\n"
            + "                                                    <td align='center' valign='top'\n"
            + "                                                        style='padding:0;Margin:0;width:640px'>\n"
            + "                                                        <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                            style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                            <tr class='es-visible-simple-html-only'\n"
            + "                                                                style='border-collapse:collapse'>\n"
            + "                                                                <td align='center'\n"
            + "                                                                    style='padding:0;Margin:0;font-size:0px'><img\n"
            + "                                                                        class='adapt-img'\n"
            + "                                                                        src='https://lh3.googleusercontent.com/proxy/59GmMKXLf5LRpgAJ8JhK8boCq9LKIVTbWsBozoNghJCd13sywmRumDxnUu2w3Xy3JORuPoYWJLJTEz7Abg-W7Stw0YBKSncTGz3AkA-1LgGlXLSWyRfVeFXyy4hj'\n"
            + "                                                                        alt\n"
            + "                                                                        style='display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic'\n"
            + "                                                                        width='640'></td>\n"
            + "                                                            </tr>\n"
            + "                                                        </table>\n"
            + "                                                    </td>\n"
            + "                                                </tr>\n"
            + "                                            </table>\n"
            + "                                        </td>\n"
            + "                                    </tr>\n"
            + "                                    <tr style='border-collapse:collapse'>\n"
            + "                                        <td align='left' style='padding:0;Margin:0;padding-top:30px'>\n"
            + "                                            <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                <tr style='border-collapse:collapse'>\n"
            + "                                                    <td align='center' valign='top'\n"
            + "                                                        style='padding:0;Margin:0;width:640px'>\n"
            + "                                                        <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                            style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                            <tr style='border-collapse:collapse'>\n"
            + "                                                                <td align='center' style='padding:0;Margin:0'>\n"
            + "                                                                    <h1\n"
            + "                                                                        style='Margin:0;line-height:36px;mso-line-height-rule:exactly;font-family:tahoma, verdana, segoe, sans-serif;font-size:30px;font-style:normal;font-weight:bold;color:#000000'>\n"
            + "                                                                        Nouveau event</h1>\n"
            + "                                                                </td>\n"
            + "                                                            </tr>\n"
            + "                                                            <tr style='border-collapse:collapse'>\n"
            + "                                                                <td align='center'\n"
            + "                                                                    style='padding:0;Margin:0;padding-top:15px'>\n"
            + "                                                                    <p style='Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, '\n"
            + "                                                                        helvetica neue', helvetica,\n"
            + "                                                                        sans-serif;line-height:21px;color:#333333;font-size:14px'>\n"
            + "                                                                        Bienvenu Ms/Mm ";
    //**************************************************************************************
    
    
    
    
   public String nom_user ;
    
    
    
    
    //***************************************************************************************
    public static String s3 = " dans notre platforme\n"
            + "                                                                        FanArt nous vous propose une nouvelles evenement\n"
            + "                                                                        trés Intéressant.</p>\n"
            + "                                                                </td>\n"
            + "                                                            </tr>\n"
            + "                                                        </table>\n"
            + "                                                    </td>\n"
            + "                                                </tr>\n"
            + "                                            </table>\n"
            + "                                        </td>\n"
            + "                                    </tr>\n"
            + "                                    <tr style='border-collapse:collapse'>\n"
            + "                                        <td align='left' style='padding:0;Margin:0'>\n"
            + "                                            <table width='100%' cellspacing='0' cellpadding='0'\n"
            + "                                                style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                <tr style='border-collapse:collapse'>\n"
            + "                                                    <td valign='top' align='center'\n"
            + "                                                        style='padding:0;Margin:0;width:640px'>\n"
            + "                                                        <table width='100%' cellspacing='0' cellpadding='0'\n"
            + "                                                            style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                        </table>\n"
            + "                                                    </td>\n"
            + "                                                </tr>\n"
            + "                                            </table>\n"
            + "                                        </td>\n"
            + "                                    </tr>\n"
            + "                                </table>\n"
            + "                            </td>\n"
            + "                        </tr>\n"
            + "                    </table>\n"
            + "                    <table cellpadding='0' cellspacing='0' class='es-footer' align='center'\n"
            + "                        style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top'>\n"
            + "                        <tr style='border-collapse:collapse'>\n"
            + "                            <td align='center' style='padding:0;Margin:0'>\n"
            + "                                <table bgcolor='#ffffff' class='es-footer-body' align='center' cellpadding='0'\n"
            + "                                    cellspacing='0'\n"
            + "                                    style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;border-top:1px solid #DDDDF0;width:640px'>\n"
            + "                                    <tr style='border-collapse:collapse'>\n"
            + "                                        <td align='left' style='padding:0;Margin:0;padding-top:30px'>\n"
            + "                                            <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                <tr style='border-collapse:collapse'>\n"
            + "                                                    <td align='center' valign='top'\n"
            + "                                                        style='padding:0;Margin:0;width:640px'>\n"
            + "                                                        <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                            style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                            <tr style='border-collapse:collapse'>\n"
            + "                                                                <td align='center'\n"
            + "                                                                    style='padding:0;Margin:0;padding-top:20px;font-size:0'>\n"
            + "                                                                    <table cellpadding='0' cellspacing='0'\n"
            + "                                                                        class='es-table-not-adapt es-social'\n"
            + "                                                                        style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                                        <tr style='border-collapse:collapse'>\n"
            + "                                                                            <td align='center' valign='top'\n"
            + "                                                                                style='padding:0;Margin:0;padding-right:20px'>\n"
            + "                                                                                <img title='Facebook'\n"
            + "                                                                                    src='https://www.facebook.com/monam.bengouta.9/'\n"
            + "                                                                                    alt='Fb' width='32'\n"
            + "                                                                                    style='display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;font-size:12px'>\n"
            + "                                                                            </td>\n"
            + "                                                                            <td align='center' valign='top'\n"
            + "                                                                                style='padding:0;Margin:0;padding-right:20px'>\n"
            + "                                                                                <img title='Twitter'\n"
            + "                                                                                    src=''\n"
            + "                                                                                    alt='Tw' width='32'\n"
            + "                                                                                    style='display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;font-size:12px'>\n"
            + "                                                                            </td>\n"
            + "                                                                            <td align='center' valign='top'\n"
            + "                                                                                style='padding:0;Margin:0;padding-right:20px'>\n"
            + "                                                                                <img title='Instagram'\n"
            + "                                                                                    src='https://www.instagram.com/monaambengouta/'\n"
            + "                                                                                    alt='Inst' width='32'\n"
            + "                                                                                    style='display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;font-size:12px'>\n"
            + "                                                                            </td>\n"
            + "                                                                            <td align='center' valign='top'\n"
            + "                                                                                style='padding:0;Margin:0'><img\n"
            + "                                                                                    title='Youtube'\n"
            + "                                                                                    src='https://www.youtube.com/channel/UC1yOKqlWKZLG7gX23bqiiVA'\n"
            + "                                                                                    alt='Yt' width='32'\n"
            + "                                                                                    style='display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;font-size:12px'>\n"
            + "                                                                            </td>\n"
            + "                                                                        </tr>\n"
            + "                                                                    </table>\n"
            + "                                                                </td>\n"
            + "                                                            </tr>\n"
            + "                                                        </table>\n"
            + "                                                    </td>\n"
            + "                                                </tr>\n"
            + "                                            </table>\n"
            + "                                        </td>\n"
            + "                                    </tr>\n"
            + "                                    <tr style='border-collapse:collapse'>\n"
            + "                                        <td align='left'\n"
            + "                                            style='padding:0;Margin:0;padding-bottom:20px;padding-top:30px'>\n"
            + "                                            <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                <tr style='border-collapse:collapse'>\n"
            + "                                                    <td align='center' valign='top'\n"
            + "                                                        style='padding:0;Margin:0;width:640px'>\n"
            + "                                                        <table cellpadding='0' cellspacing='0' width='100%'\n"
            + "                                                            style='mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px'>\n"
            + "                                                            <tr class='es-visible-simple-html-only'\n"
            + "                                                                style='border-collapse:collapse'>\n"
            + "                                                                <td align='center' style='padding:0;Margin:0'>\n"
            + "                                                                    <p style='Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, '\n"
            + "                                                                        helvetica neue', helvetica,\n"
            + "                                                                        sans-serif;line-height:18px;color:#333333;font-size:12px'>\n"
            + "                                                                        <a target='_blank' href=''\n"
            + "                                                                            style='-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:12px'>Contact</a>\n"
            + "                                                                        | <a target='_blank'\n"
            + "                                                                            href=''\n"
            + "                                                                            style='-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:12px'>Privacy</a>\n"
            + "                                                                        | <a target='_blank'\n"
            + "                                                                            href=''\n"
            + "                                                                            style='-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:12px'>About</a>\n"
            + "                                                                        | <a target='_blank'\n"
            + "                                                                            href=''\n"
            + "                                                                            class='unsubscribe'\n"
            + "                                                                            style='-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:12px'>Unsubscribe</a>\n"
            + "                                                                    </p>\n"
            + "                                                                </td>\n"
            + "                                                            </tr>\n"
            + "                                                        </table>\n"
            + "                                                    </td>\n"
            + "                                                </tr>\n"
            + "                                            </table>\n"
            + "                                        </td>\n"
            + "                                    </tr>\n"
            + "                                </table>\n"
            + "                            </td>\n"
            + "                        </tr>\n"
            + "                    </table>\n"
            + "                </td>\n"
            + "            </tr>\n"
            + "        </table>\n"
            + "    </div>\n"
            + "</body>\n"
            + "\n"
            + "</html>";
    
    
    public String mail_contenu ;
    public Newmailevent() {
    }

    public Newmailevent(String s2) {
        this.nom_user = s2;
    }

    public String getMail_contenu() {
        return s1+""+nom_user+""+s3;
    }

    public void setNom_user(String nom_user) {
        this.nom_user = nom_user;
    }
    

  
    
    
    
    
    

}
